global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Microsoft.EntityFrameworkCore;
global using MobileShop.Dal.EfStructures;
global using MobileShop.Dal.Initialization;
global using MobileShop.Models.Enums;
global using MobileShop.Models.Entities;
global using System.ComponentModel.DataAnnotations;
global using MobileShop.Models.ViewModels.Web;
global using MobileShop.Models.ViewModels.Web.BindModels;
global using MobileShop.Services;
global using MobileShop.Services.DataServices.Interfaces;
global using MobileShop.Services.Logging.Configuration;
global using MobileShop.Services.Security;
global using MobileShop.Web;
global using MobileShop.Web.Extensions;
global using System.Diagnostics;
global using static Microsoft.AspNetCore.Builder.WebApplication;
