<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MobileShop.Models\MobileShop.Models.csproj">
      <AdditionalProperties Condition="'$(RuntimeIdentifier)' != ''">DebugSymbols=false;DebugType=None</AdditionalProperties>
    </ProjectReference>
    <ProjectReference Include="..\MobileShop.Dal\MobileShop.Dal.csproj">
      <AdditionalProperties Condition="'$(RuntimeIdentifier)' != ''">DebugSymbols=false;DebugType=None</AdditionalProperties>
    </ProjectReference>
    <ProjectReference Include="..\MobileShop.Services\MobileShop.Services.csproj">
      <AdditionalProperties Condition="'$(RuntimeIdentifier)' != ''">DebugSymbols=false;DebugType=None</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <PublishDir>$(MSBuildThisFileDirectory)..\..\Publishes\$(RuntimeIdentifier)\</PublishDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' != ''">
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
