// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileShop.Dal.EfStructures;

#nullable disable

namespace MobileShop.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MobileShop.Models.Entities.AppleId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("AppleIds");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.AppleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargeCycle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("AppleInfos");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Cable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Connector1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Connector2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Cables");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.CaseModelFit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("CaseId", "ModelId")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("CaseModelFits");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Charger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Wattage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Chargers");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.DeviceSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargeSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ram")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageCapacityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("StorageCapacityId");

                    b.ToTable("DeviceSpecs");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SharePercent")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Glass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Glasses");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.GlassModelFit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("GlassId", "ModelId")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("GlassModelFits");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Guarantee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Corporation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Guarantees");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DisplaySize")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId", "Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IMEI1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMEI2")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OwnershipTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("IMEI1")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.PortableStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageCapacityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("StorageCapacityId");

                    b.ToTable("PortableStorages");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.PowerBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityMah")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxWattage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("PowerBanks");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelId");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price_NonNegative", "Price >= 0");
                        });
                });

            modelBuilder.Entity("MobileShop.Models.Entities.SecondHand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestPeriodDays")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int?>("UsedDurationDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("SecondHands");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.SmartWatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("SmartWatches");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.StorageCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Gb")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("StorageCapacities");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Tablet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Tablets");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FinishedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_FinishedPrice_NonNegative", "FinishedPrice >= 0");
                        });
                });

            modelBuilder.Entity("MobileShop.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.AppleId", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("AppleIdProfile")
                        .HasForeignKey("MobileShop.Models.Entities.AppleId", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.AppleInfo", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("AppleInfoProfile")
                        .HasForeignKey("MobileShop.Models.Entities.AppleInfo", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Cable", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("CableProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Cable", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Case", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("CaseProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Case", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.CaseModelFit", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Case", "CaseNavigation")
                        .WithMany("ModelFits")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobileShop.Models.Entities.Model", "ModelNavigation")
                        .WithMany("CaseFits")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CaseNavigation");

                    b.Navigation("ModelNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Charger", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("ChargerProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Charger", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Customer", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Person", "PersonNavigation")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Customer", "PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PersonNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.DeviceSpec", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("DeviceSpecProfile")
                        .HasForeignKey("MobileShop.Models.Entities.DeviceSpec", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobileShop.Models.Entities.StorageCapacity", "StorageCapacityNavigation")
                        .WithMany("DeviceSpecs")
                        .HasForeignKey("StorageCapacityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");

                    b.Navigation("StorageCapacityNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Employee", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Person", "PersonNavigation")
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Glass", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("GlassProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Glass", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.GlassModelFit", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Glass", "GlassNavigation")
                        .WithMany("ModelFits")
                        .HasForeignKey("GlassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobileShop.Models.Entities.Model", "ModelNavigation")
                        .WithMany("GlassFits")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GlassNavigation");

                    b.Navigation("ModelNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Guarantee", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("GuaranteeProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Guarantee", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Laptop", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("LaptopProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Laptop", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Model", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Category", "CategoryNavigation")
                        .WithMany("Models")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobileShop.Models.Entities.Manufacturer", "ManufacturerNavigation")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CategoryNavigation");

                    b.Navigation("ManufacturerNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Phone", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("PhoneProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Phone", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.PortableStorage", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("PortableStorageProfile")
                        .HasForeignKey("MobileShop.Models.Entities.PortableStorage", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobileShop.Models.Entities.StorageCapacity", "StorageCapacityNavigation")
                        .WithMany("PortableStorages")
                        .HasForeignKey("StorageCapacityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");

                    b.Navigation("StorageCapacityNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.PowerBank", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("PowerBankProfile")
                        .HasForeignKey("MobileShop.Models.Entities.PowerBank", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Product", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Color", "ColorNavigation")
                        .WithMany("Products")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MobileShop.Models.Entities.Model", "ModelNavigation")
                        .WithMany("Products")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ColorNavigation");

                    b.Navigation("ModelNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.SecondHand", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("SecondHandProfile")
                        .HasForeignKey("MobileShop.Models.Entities.SecondHand", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Seller", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Person", "PersonNavigation")
                        .WithOne("SellerProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Seller", "PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PersonNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.SmartWatch", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("SmartWatchProfile")
                        .HasForeignKey("MobileShop.Models.Entities.SmartWatch", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Tablet", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithOne("TabletProfile")
                        .HasForeignKey("MobileShop.Models.Entities.Tablet", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Transaction", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Customer", "CustomerNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobileShop.Models.Entities.Product", "ProductNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MobileShop.Models.Entities.Seller", "SellerNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CustomerNavigation");

                    b.Navigation("ProductNavigation");

                    b.Navigation("SellerNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.User", b =>
                {
                    b.HasOne("MobileShop.Models.Entities.Person", "PersonNavigation")
                        .WithOne("UserProfile")
                        .HasForeignKey("MobileShop.Models.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PersonNavigation");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Case", b =>
                {
                    b.Navigation("ModelFits");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Category", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Color", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Customer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Glass", b =>
                {
                    b.Navigation("ModelFits");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Model", b =>
                {
                    b.Navigation("CaseFits");

                    b.Navigation("GlassFits");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Person", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("EmployeeProfile");

                    b.Navigation("SellerProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Product", b =>
                {
                    b.Navigation("AppleIdProfile");

                    b.Navigation("AppleInfoProfile");

                    b.Navigation("CableProfile");

                    b.Navigation("CaseProfile");

                    b.Navigation("ChargerProfile");

                    b.Navigation("DeviceSpecProfile");

                    b.Navigation("GlassProfile");

                    b.Navigation("GuaranteeProfile");

                    b.Navigation("LaptopProfile");

                    b.Navigation("PhoneProfile");

                    b.Navigation("PortableStorageProfile");

                    b.Navigation("PowerBankProfile");

                    b.Navigation("SecondHandProfile");

                    b.Navigation("SmartWatchProfile");

                    b.Navigation("TabletProfile");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.Seller", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MobileShop.Models.Entities.StorageCapacity", b =>
                {
                    b.Navigation("DeviceSpecs");

                    b.Navigation("PortableStorages");
                });
#pragma warning restore 612, 618
        }
    }
}
